#!/bin/bash
echo "Docker initializer"
while getopts ":b:p:" optname
	do
		case "$optname" in
			"b")
				branchName=$OPTARG
				;;
			"p")
				profile=$OPTARG
				;;
		esac
done

if ! [[ -v branchName ]]
then
	branchName="master"
fi

if ! [[ -v profile ]]
then
	profile="dev"
fi

echo "Branch name: $branchName"
echo "Profile name: $profile"

echo "Creating dockerfile..."

cd ~

if [ -f Dockerfile ]
then
	>Dockerfile
else
	touch Dockerfile
fi

echo "FROM maven" >> Dockerfile

if [ -d ".m2" ]; then
        echo "COPY .m2 /root/.m2" >> Dockerfile
fi

if [ $profile = "prod" ]
then
	databaseIp="$(sudo docker inspect --format '{{ .NetworkSettings.IPAddress }}' employee-db)"
	environmentLine="JDBC_DATABASE_URL=$databaseIp:5432/springbootdb"
	echo "ENV $environmentLine"
	echo "ENV $environmentLine" >> Dockerfile
fi


echo "RUN git clone https://github.com/bartosz-pigla/employeeManagement && cd employeeManagement && git checkout $branchName" >> Dockerfile
echo "EXPOSE 8080" >> Dockerfile

if [ -f add-maven.sh ]
then
        >add-maven.sh
else
        touch add-maven.sh
fi

echo "Dockerfile created. Running container..."
sudo docker build -t employee-project-image .
sudo docker run --name employee-project -v /home/bartek/.m2:/root/.m2 -it employee-project-image /bin/sh -c "cd employeeManagement; mvn spring-boot:run -Drun.profiles=$(echo "$profile")"
