DROP TABLE IF EXISTS EMPLOYEE;

CREATE TABLE EMPLOYEE (
   EMPLOYEE_ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
   FIRST_NAME VARCHAR(30) NOT NULL,
   LAST_NAME VARCHAR(50) NOT NULL,
   DATE_OF_EMPLOYMENT DATE NOT NULL,
   LEADER_ID INT,
   CONSTRAINT FK_LEADER_SUBORDINATE FOREIGN KEY (LEADER_ID) REFERENCES EMPLOYEE(EMPLOYEE_ID)
);